<?php

namespace Database\Seeders;

use App\Models\Project;
use Database\Seeders\Concerns\AppliesTranslations;
use Illuminate\Database\Seeder;

class ProjectIdTranslationSeeder extends Seeder
{
    use AppliesTranslations;

    public function run(): void
    {
        $this->apply(Project::class, 'slug', [
            'update-larap-for-pltp-mataloko-20-mw-and-pltp-ulumbu-20-mw-geothermal-power-plant-project-kfw-development-bank' => [
                'name_id' => 'Pemutakhiran LARAP untuk Proyek PLTP Mataloko (20 MW) dan PLTP Ulumbu (20 MW) – KfW Development Bank',
                'description_id' => '<p>Sebagai bagian dari pengembangan pembangkit listrik tenaga panas bumi Mataloko 20 MW dan Ulumbu 20 MW di Pulau Flores, penugasan konsultansi ini mencakup pemutakhiran Land Acquisition and Resettlement Action Plan (LARAP) untuk keseluruhan lingkup proyek, termasuk infrastruktur penunjang seperti jalur transmisi, jalan akses, area borrow/pit, kamp pekerja, dan zona staging.&nbsp;<br>Pekerjaan kami meliputi:</p><ul><li data-list-item-id="e315ee75d882a968b54b75b898902788d">Survei sosial-ekonomi, sensus, dan inventarisasi aset (IOL), dengan elemen yang responsif gender.&nbsp;</li><li data-list-item-id="e24285178e2a4b23bdbc98e0c7d2a7320">Perencanaan keterlibatan pemangku kepentingan (SEP), proses Free, Prior and Informed Consent (FPIC) dengan Masyarakat Adat, serta perancangan mekanisme penanganan keluhan (GRM).&nbsp;</li><li data-list-item-id="e4f5b4e317a89b4f2659b2350e5ce3619">Pemutakhiran LARAP secara terperinci, mencakup pengaturan kelembagaan, peta jalan implementasi, langkah-langkah pemulihan penghidupan, dan pengungkapan temuan.&nbsp;</li></ul><p>Dengan menyajikan dokumentasi perlindungan sosial dan lingkungan yang kuat serta rencana yang siap diimplementasikan, proyek ini mendukung PT PLN dalam melaksanakan proyek pembangkit listrik panas bumi secara bertanggung jawab secara sosial, transparan, dan berkelanjutan.</p>',
            ],
            'external-social-safeguard-monitoring-for-cw-1-2-3-4a-and-4b-under-flood-management-in-selected-river-basin-sector-project-fmsrbsp' => [
                'name_id' => 'Pemantauan Eksternal Perlindungan Sosial untuk CW - 1, 2, 3, 4A dan 4B di bawah Flood Management in Selected River Basin Sector Project (FMSRBSP)',
                'description_id' => '<p style="text-align:justify;">Sebagai bagian dari <strong>Flood Management in Selected River Basin Sector Project (FMSRBSP)</strong>, paket pekerjaan ini menyediakan <strong>Pemantauan Eksternal Perlindungan Sosial yang independen</strong> untuk paket konstruksi CW-1, CW-2, CW-3, CW-4A, dan CW-4B di Provinsi Banten dan Maluku.</p><p style="text-align:justify;">Kegiatan pemantauan mencakup verifikasi instrumen pengadaan tanah dan permukiman kembali, kajian implementasi <strong>Land Acquisition and Resettlement Plan (LARP)</strong>, evaluasi pemulihan penghidupan, verifikasi mekanisme penanganan keluhan, serta tinjauan langkah-langkah mitigasi sosial pada tingkat rumah tangga dan komunitas.</p><p style="text-align:justify;">Metodologi melibatkan verifikasi lapangan, validasi basis data (termasuk <strong>Detailed Measurement Survey / Inventory of Losses</strong>), dan wawancara pemangku kepentingan. Hasil pemantauan disajikan melalui laporan berkala yang memuat temuan, rekomendasi strategis, dan perbaikan implementasi untuk memperkuat kepatuhan terhadap kerangka kebijakan nasional dan <strong>standar perlindungan ADB</strong>, sehingga investasi pengelolaan banjir dilaksanakan secara akuntabel, berkeadilan, dan berkelanjutan.</p>',
            ],
            'socio-economic-baseline-survey-for-esia-larap-and-sep-preparation-for-the-indonesia-batambintan' => [
                'name_id' => 'Survei Dasar Sosial-Ekonomi untuk Penyusunan ESIA, LARAP dan SEP Proyek Indonesia Batam‑Bintan',
                'description_id' => '<p style="text-align:justify;">Sebagai bagian dari tahap persiapan Proyek Jembatan Batam-Bintan, layanan konsultansi ini melaksanakan <strong>survei dasar sosial-ekonomi</strong> yang komprehensif untuk mendukung penyusunan Environmental &amp; Social Impact Assessment (ESIA), Land Acquisition and Resettlement Action Plan (LARAP), dan Stakeholder Engagement Plan (SEP). Survei mencakup rumah tangga dan komunitas terdampak di Pulau Batam dan Pulau Bintan, dengan menghimpun data sosial-ekonomi terpilah gender, kelompok rentan, kepemilikan tanah dan aset, kondisi penghidupan, serta persepsi masyarakat. Temuan akan menjadi dasar penyusunan kerangka kompensasi, program pemulihan penghidupan, mekanisme penanganan keluhan (GRM), dan strategi konsultasi pemangku kepentingan. Dengan membangun data dasar yang kuat, proyek ini memastikan keselarasan dengan regulasi nasional dan persyaratan perlindungan internasional, sehingga mendorong implementasi infrastruktur jembatan Batam-Bintan yang inklusif, transparan, dan berkelanjutan.</p>',
            ],
            'location-determination-and-land-acquisition-planning-documents-penlok-bahodopi-penloklarap-fel3-esia-pomalaa' => [
                'name_id' => 'Penetapan Lokasi dan Dokumen Perencanaan Pengadaan Tanah — Penlok Bahodopi & Penlok/LARAP-FEL3 (ESIA) Pomalaa',
                'description_id' => '<p style="text-align: justify;" data-start="640" data-end="1030">Dalam mendukung pengembangan strategis peleburan dan pengolahan nikel di Bahodopi (Sulawesi Tengah) dan Pomalaa (Sulawesi Tenggara), penugasan konsultansi ini menyediakan layanan independen untuk penetapan lokasi (Penlok), penyusunan dokumen perencanaan pengadaan tanah (LARAP/FEL3), dan Environmental &amp; Social Impact Assessment (ESIA) untuk kedua lokasi tersebut.<br data-start="1006" data-end="1009">Lingkup pekerjaan meliputi:</p>
<ul style="text-align: justify;" data-start="1031" data-end="1801">
<li data-start="1031" data-end="1146">
<p data-start="1033" data-end="1146">Menetapkan dan memvalidasi lokasi optimal untuk infrastruktur proyek di Bahodopi dan Pomalaa (tugas Penlok).</p>
</li>
<li data-start="1147" data-end="1282">
<p data-start="1149" data-end="1282">Melaksanakan perencanaan pengadaan tanah (LARAP/FEL3) termasuk inventarisasi kerugian, kerangka hak (entitlement), dan strategi permukiman kembali.</p>
</li>
<li data-start="1283" data-end="1456">
<p data-start="1285" data-end="1456">Melaksanakan ESIA yang selaras dengan standar perlindungan nasional dan internasional&mdash;mengkaji risiko lingkungan dan sosial, dampak terhadap pemangku kepentingan, serta langkah-langkah mitigasi.</p>
</li>
<li data-start="1457" data-end="1658">
<p data-start="1459" data-end="1658">Merancang mekanisme penanganan keluhan (GRM) dan rencana keterlibatan pemangku kepentingan (SEP) untuk memastikan partisipasi dan responsivitas masyarakat selama proses pengadaan tanah, relokasi, atau kompensasi.</p>
</li>
<li data-start="1659" data-end="1801">
<p data-start="1661" data-end="1801">Mendukung klien dalam memperoleh izin lingkungan yang diperlukan serta menyelaraskannya dengan persyaratan regulasi dan keberlanjutan korporat.</p>
</li>
</ul>
<p style="text-align: justify;" data-start="1803" data-end="2102">Dengan memadukan perencanaan pengadaan tanah yang teknis dan standar perlindungan sosial dan lingkungan yang tinggi, konsultansi ini memastikan bahwa pengembangan Bahodopi dan Pomalaa disusun di atas fondasi izin sosial yang bertanggung jawab, kompensasi yang berkeadilan, dan hubungan masyarakat yang berkelanjutan.</p>',
            ],
            'consultancy-services-for-the-preparation-of-larap-study-and-land-acquisition-planning-documents-matenggeng-pumped-storage-943-mw' => [
                'name_id' => 'Layanan Konsultansi untuk Penyusunan Studi LARAP dan Dokumen Perencanaan Pengadaan Tanah – Matenggeng Pumped Storage 943 MW',
                'description_id' => '<p data-start="297" data-end="614">Proyek MPSPP direncanakan memiliki kapasitas 943 MW, berlokasi di Kabupaten Ciamis dan Kabupaten Kuningan di Provinsi Jawa Barat, serta Kabupaten Cilacap di Provinsi Jawa Tengah. Proyek ini mencakup pembangunan Bendungan Atas (Upper Dam) dan Bendungan Bawah (Lower Dam), yang masing-masing berlokasi di Sungai Cimancing dan Sungai Citetel, yang keduanya mengalir ke Sungai Cijolang, anak Sungai Citanduy.</p>
<h3 data-start="825" data-end="839">Tujuan</h3>
<p>Tujuan utama adalah menyusun Land Acquisition and Resettlement Action Plan (LARAP) yang komprehensif untuk Proyek Pembangkit Listrik Tenaga Pumped Storage Matenggeng. Rencana ini akan dikembangkan dengan selaras sepenuhnya dengan Environmental and Social Standard 5 World Bank (ESS5: Land Acquisition, Restrictions on Land Use and Involuntary Resettlement) serta peraturan perundang-undangan Indonesia yang relevan, termasuk Undang-Undang No. 2 Tahun 2012 tentang Pengadaan Tanah bagi Pembangunan untuk Kepentingan Umum beserta peraturan turunannya. LARAP akan berfungsi sebagai panduan strategis dan operasional untuk memastikan bahwa proses pengadaan tanah dan permukiman kembali dilaksanakan secara transparan dan berkeadilan, memitigasi dampak sosial-ekonomi yang merugikan, serta memastikan bahwa Project-Affected Persons (PAPs) menerima kompensasi dan bantuan yang adil untuk memperbaiki, atau sekurang-kurangnya memulihkan, penghidupan dan taraf hidup mereka ke tingkat sebelum proyek.</p>
<h3 data-start="1126" data-end="1147">Lingkup Layanan</h3>
<p data-start="1641" data-end="1795">Lingkup layanan mencakup seluruh tahapan yang diperlukan untuk penyusunan dan perencanaan LARAP, dengan memastikan kepatuhan terhadap hukum Indonesia maupun standar World Bank ESS5. Kegiatan tersebut meliputi:</p>
<ul>
<li data-start="1641" data-end="1795">Identifikasi dan Pemetaan Area Terdampak: Melaksanakan identifikasi dan pemetaan terperinci atas seluruh bidang tanah dan aset dalam tapak proyek, mencakup Bendungan Atas dan Bendungan Bawah, fasilitas penunjang (jalan akses, quarry), dan koridor jalur transmisi 500 kV sepanjang 30 km, termasuk Right-of-Way (RoW)-nya.</li>
<li data-start="1641" data-end="1795">Survei Sosial-Ekonomi dan Kajian Kerentanan: Melaksanakan sensus dan Inventory of Losses (IOL) yang komprehensif untuk seluruh PAPs guna menghimpun data dasar sosial-ekonomi. Lingkup ini mencakup identifikasi kelompok rentan (seperti rumah tangga berpenghasilan rendah, lansia, rumah tangga dengan kepala keluarga perempuan, dan kelompok masyarakat adat) yang mungkin memerlukan bantuan tambahan.</li>
<li data-start="1641" data-end="1795">Konsultasi Publik dan Pengungkapan Informasi: Merencanakan dan melaksanakan proses konsultasi yang bermakna dengan PAPs dan pemangku kepentingan lainnya sepanjang penyusunan LARAP. Hal ini mencakup pengungkapan informasi proyek yang relevan dalam format yang mudah diakses dan dipahami untuk memastikan partisipasi mereka dalam proses perencanaan, sebagaimana diwajibkan oleh kedua kerangka acuan.</li>
<li data-start="1641" data-end="1795">Penyusunan Entitlement Matrix dan Penilaian: Mengembangkan entitlement matrix terperinci yang menjembatani kesenjangan antara regulasi Indonesia dan persyaratan World Bank ESS5. Matriks ini akan mendefinisikan kelayakan kompensasi dan bantuan lainnya untuk setiap kategori kerugian, dengan memastikan bahwa kompensasi atas aset diberikan sebesar biaya penggantian penuh (full replacement cost) dan dianggap "layak dan adil" sesuai hukum nasional.</li>
<li data-start="1641" data-end="1795">Perencanaan Permukiman Kembali dan Pemulihan Penghidupan: Merancang Rencana Permukiman Kembali yang komprehensif untuk rumah tangga yang terdampak secara fisik serta Program Pemulihan Penghidupan untuk seluruh PAPs yang memenuhi syarat. Program ini dirancang untuk memperbaiki atau sekurang-kurangnya memulihkan tingkat pendapatan dan taraf hidup melalui dukungan yang disesuaikan, seperti bantuan pertanian, pelatihan keterampilan, atau akses terhadap kredit.</li>
<li data-start="1641" data-end="1795">Mekanisme Penanganan Keluhan (GRM): Membentuk GRM khusus proyek yang sesuai secara budaya, mudah diakses, dan responsif. Mekanisme ini akan tersedia bagi seluruh PAPs, termasuk kelompok rentan, tanpa biaya, untuk menangani dan menyelesaikan kekhawatiran dan keluhan terkait proyek secara efektif.</li>
<li data-start="1641" data-end="1795">Rencana Implementasi, Anggaran, dan Kerangka Pemantauan: Menyusun jadwal implementasi terperinci, anggaran yang komprehensif untuk seluruh kegiatan LARAP (termasuk program kompensasi dan pemulihan), serta kerangka pemantauan dan evaluasi internal dan eksternal untuk memastikan tercapainya tujuan LARAP.</li>
</ul>',
            ],
            'consultancy-services-on-land-acquisition-and-resettlement-action-plan-larap-phase-ii-mentarang-induk-hydroelectric-project-mihep' => [
                'name_id' => 'Layanan Konsultansi Land Acquisition and Resettlement Action Plan (LARAP) Phase II — Mentarang Induk Hydroelectric Project (MIHEP)',
                'description_id' => '<p style="text-align: justify;" data-start="503" data-end="1449">Sebagai bagian dari pengembangan Mentarang Induk Hydroelectric Project (MIHEP) di Kalimantan Utara, konsultansi ini mencakup studi tahap kedua atas Land Acquisition and Resettlement Action Plan (LARAP). Penugasan ini menangani dampak permukiman kembali yang signifikan &mdash; baik perpindahan fisik maupun kerugian ekonomi &mdash; yang timbul dari fasilitas pembangkit listrik tenaga air berskala besar dan infrastruktur terkait. Lingkup pekerjaan mencakup perancangan kebijakan kompensasi, program pemulihan penghidupan, validasi prosedur pengadaan tanah, kajian interaksi dengan komunitas penerima (host community), konsultasi dengan masyarakat terdampak, serta pembentukan mekanisme penanganan keluhan dan penyelesaian sengketa. Studi ini dilaksanakan sesuai dengan kerangka hukum Indonesia dan diselaraskan dengan standar praktik terbaik internasional seperti Hydropower Sustainability Guidelines, IFC Performance Standards, dan Equator Principles.</p>
<p style="text-align: justify;" data-start="1451" data-end="1857">Melalui upaya ini, proyek mendukung PT Kayan Hydropower Nusantara dalam membangun kerangka permukiman kembali yang terstruktur dan berkeadilan yang melindungi hak dan kesejahteraan masyarakat terdampak, memastikan pengadaan tanah yang transparan, memberikan kompensasi yang adil, memulihkan penghidupan, dan memperkuat ketahanan masyarakat &mdash; sehingga menanamkan keberlanjutan sosial ke dalam inisiatif pembangkit listrik tenaga air yang lebih luas.</p>',
            ],
            'preparation-of-land-acquisition-planning-document-dppt-and-feasibility-study-for-kamal-north-jakarta-and-rawa-lindung-south-jakarta-reservoir-development-plan' => [
                'name_id' => 'Penyusunan Dokumen Perencanaan Pengadaan Tanah (DPPT) dan Studi Kelayakan untuk Rencana Pengembangan Waduk Kamal (Jakarta Utara) dan Rawa Lindung (Jakarta Selatan)',
                'description_id' => '<p style="text-align: justify;" data-start="580" data-end="1139">Proyek konsultansi ini mendukung <strong data-start="618" data-end="651">Pemerintah Provinsi DKI Jakarta</strong> melalui <strong data-start="664" data-end="709">Dinas Sumber Daya Air (Dinas SDA)</strong> dalam menyusun <strong data-start="727" data-end="794">Studi Kelayakan dan Dokumen Perencanaan Pengadaan Tanah (DPPT)</strong> untuk rencana pengembangan <strong data-start="827" data-end="863">Waduk Kamal di Jakarta Utara</strong> dan <strong data-start="868" data-end="911">Waduk Rawa Lindung di Jakarta Selatan</strong>. Studi ini bertujuan mengevaluasi kelayakan teknis, lingkungan, dan sosial-ekonomi pengembangan waduk, termasuk kebutuhan pengadaan tanah, implikasi permukiman kembali, dan langkah-langkah pengelolaan lingkungan.</p>
<p style="text-align: justify;" data-start="1141" data-end="1495">Komponen DPPT mencakup pemetaan bidang tanah terdampak, identifikasi kepemilikan, dan estimasi kebutuhan kompensasi sesuai dengan regulasi pengadaan tanah Indonesia dan prinsip perlindungan sosial. Studi kelayakan selanjutnya mengkaji fungsi hidrologis, alternatif desain rekayasa, serta potensi dampak sosial dan lingkungan.</p>
<p style="text-align: justify;" data-start="1497" data-end="1708">Dengan memadukan analisis teknis, sosial, dan lingkungan, proyek ini menyediakan kerangka perencanaan yang komprehensif untuk mendukung pengelolaan air perkotaan yang berkelanjutan dan infrastruktur pengendalian banjir di Jakarta.</p>',
            ],
            'consultancy-services-for-the-preparation-of-dp3-dokumen-proposal-proyek-prakarsa-pluit-to-airport-toll-road-pluitbandara-and-utilities' => [
                'name_id' => 'Layanan Konsultansi untuk Penyusunan DP3 (Dokumen Proposal Proyek Prakarsa) – Jalan Tol Pluit ke Bandara (Pluit–Bandara) dan Utilitas',
                'description_id' => '<p style="text-align: justify;" data-start="514" data-end="816">Dalam inisiatif strategis untuk mengembangkan koridor jalan tol Pluit&ndash;Bandara dan pekerjaan utilitas terkait, penugasan konsultansi ini mendukung penyusunan <strong data-start="684" data-end="726">DP3 (Dokumen Proposal Proyek Prakarsa)</strong> dan dokumen perencanaan pengadaan tanah (DPPT) terkait. Lingkup pekerjaan meliputi:</p>
<ul style="text-align: justify;" data-start="817" data-end="1646">
<li data-start="817" data-end="1028">
<p data-start="819" data-end="1028">Menyusun DPPT sebagai masukan integral bagi DP3, dengan merinci strategi pengadaan tanah, implikasi perubahan tata guna lahan, kebutuhan relokasi utilitas, dan jadwal awal pengadaan serta pembebasan lahan.</p>
</li>
<li data-start="1029" data-end="1230">
<p data-start="1031" data-end="1230">Melaksanakan kajian dasar atas bidang tanah eksisting, infrastruktur utilitas, rights-of-way, dan aset terdampak di sepanjang koridor Pluit&ndash;Bandara (mencakup sebagian wilayah DKI Jakarta dan Banten).</p>
</li>
<li data-start="1231" data-end="1427">
<p data-start="1233" data-end="1427">Melibatkan pemangku kepentingan utama&mdash;otoritas publik, penyedia utilitas, masyarakat lokal&mdash;serta membentuk mekanisme penanganan keluhan (GRM) yang spesifik untuk pengadaan tanah dan relokasi utilitas.</p>
</li>
<li data-start="1428" data-end="1646">
<p data-start="1430" data-end="1646">Memberikan saran mengenai perencanaan implementasi, estimasi biaya pengadaan tanah dan relokasi utilitas, dengan memastikan keselarasan dengan kerangka regulasi Indonesia dan praktik terbaik untuk pengembangan infrastruktur jalan tol.</p>
</li>
</ul>
<p style="text-align: justify;" data-start="1648" data-end="2035">Melalui perencanaan yang cermat dan keselarasan pemangku kepentingan, konsultansi ini bertujuan membekali PT Citra Marga Nusaphala Persada Tbk dengan paket DP3/DPPT yang kuat guna meningkatkan kesiapan proyek, mempercepat pengadaan tanah dan relokasi utilitas, serta mendukung tahap konstruksi koridor jalan tol Pluit&ndash;Bandara dengan keterlambatan yang minimal dan implementasi yang bertanggung jawab secara sosial.</p>',
            ],
            'external-monitoring-pada-consulting-service-for-the-construction-supervision-of-patimban-access-toll-road-construction-project-jica-loan-no-ip-586' => [
                'name_id' => 'External Monitoring pada Consulting Service for The Construction Supervision of Patimban Access Toll Road Construction Project JICA Loan No. IP-586',
                'description_id' => '<p style="text-align: justify;">Sebagai bagian dari <strong>Consulting Service for the Construction Supervision of the Patimban Access Toll Road Construction Project</strong>, kegiatan ini berfokus pada <strong>Pemantauan Eksternal Perlindungan (Safeguards)</strong> untuk memastikan bahwa implementasi proyek selaras dengan prinsip keberlanjutan, kepatuhan sosial, dan perlindungan masyarakat terdampak. Pemantauan dilaksanakan secara independen, mengacu pada kerangka kebijakan nasional maupun standar perlindungan yang berlaku dari lembaga pemberi pinjaman.</p>
<p style="text-align: justify;">Lingkup pekerjaan mencakup pemantauan kemajuan pengadaan tanah dan relokasi, kajian implementasi <strong>Land Acquisition and Resettlement Action Plan (LARAP)</strong>, evaluasi pemulihan penghidupan, verifikasi mekanisme penanganan keluhan, serta mitigasi dampak sosial pada tingkat rumah tangga dan komunitas.</p>
<p style="text-align: justify;">Hasil pemantauan disajikan melalui laporan berkala yang dilengkapi rekomendasi strategis dan perbaikan implementasi berdasarkan temuan lapangan. Pendekatan ini bertujuan memastikan bahwa pengembangan Jalan Tol Patimban tidak hanya mencapai target konstruksinya, tetapi juga dilaksanakan secara akuntabel, berkeadilan, dan sesuai dengan prinsip pengelolaan dampak sosial yang bertanggung jawab.</p>',
            ],
            'consultancy-services-on-land-acquisition-and-livelihood-restoration-plan-lalrp-study-for-the-mentarang-induk-hydroelectric-project-overhead-transmission-line' => [
                'name_id' => 'Layanan Konsultansi Studi Land Acquisition and Livelihood Restoration Plan (LALRP) untuk Mentarang Induk Hydroelectric Project – Jalur Transmisi Udara',
                'description_id' => '<p style="text-align: justify;" data-start="746" data-end="1114">Sebagai bagian dari pengembangan <strong data-start="780" data-end="829">Mentarang Induk Hydroelectric Project (MIHEP)</strong> dan jalur transmisi udara 500 kV-nya, konsultansi ini menyediakan <strong data-start="902" data-end="980">Studi Land Acquisition and Livelihood Restoration Plan (LALRP) yang independen</strong> untuk memastikan bahwa proses pengadaan tanah dan perlindungan sosial dilaksanakan secara transparan, berkeadilan, dan berkelanjutan.</p>
<p style="text-align: justify;" data-start="1116" data-end="1743">Penugasan ini mencakup kajian komprehensif atas dampak pengadaan tanah dan kondisi sosial-ekonomi masyarakat terdampak, validasi <strong data-start="1266" data-end="1303">Detailed Measurement Survey (DMS)</strong> dan <strong data-start="1308" data-end="1337">Inventory of Losses (IOL)</strong>, penyusunan strategi pemulihan penghidupan, serta pengembangan kerangka untuk <strong data-start="1423" data-end="1491">penanganan keluhan, keterlibatan pemangku kepentingan, dan pemantauan sosial</strong>. Studi ini juga mengintegrasikan aspek <strong data-start="1523" data-end="1562">Cultural Heritage Management (CHMP)</strong> dan <strong data-start="1567" data-end="1604">Indigenous Peoples Planning (IPP)</strong> untuk memastikan kepatuhan penuh terhadap regulasi Indonesia dan standar perlindungan praktik terbaik internasional untuk infrastruktur pembangkit listrik tenaga air.</p>
<p style="text-align: justify;" data-start="1745" data-end="2065">Keluaran mencakup penyusunan <strong data-start="1789" data-end="1807">dokumen LALRP</strong>, peta jalan implementasi, dan rekomendasi untuk memandu klien dalam melaksanakan program pengadaan tanah dan pemulihan yang selaras dengan persyaratan nasional maupun ekspektasi internasional untuk pengembangan proyek yang bertanggung jawab dan inklusif secara sosial.</p>
<p style="text-align: justify;" data-start="2067" data-end="2373">Melalui analisis berbasis bukti dan keterlibatan lapangan, studi ini mendukung PT Kayan Hydropower Nusantara dalam mewujudkan visi MIHEP sebagai <strong data-start="2207" data-end="2243">proyek strategis nasional (PSN)</strong> yang menghadirkan energi terbarukan sekaligus menjunjung tanggung jawab sosial dan pengembangan masyarakat yang berkelanjutan di Kalimantan Utara.</p>',
            ],
            'social-safeguard-larap-and-gender-responsive-analysis-for-raw-water-intake-and-transmission-systems-kertasari-jatigede-in-west-java-lau-simeme-in-north-sumatra' => [
                'name_id' => 'Perlindungan Sosial, LARAP dan Analisis Responsif Gender untuk Sistem Intake dan Transmisi Air Baku (Kertasari & Jatigede di Jawa Barat; Lau Simeme di Sumatera Utara)',
                'description_id' => '<p style="text-align: justify;" data-start="635" data-end="1312">Dalam program penguatan infrastruktur penyediaan air baku di Indonesia&mdash;mencakup sistem Kertasari (Jawa Barat), sistem Jatigede Tahap II (Jawa Barat), dan sistem waduk/transmisi Lau Simeme (Sumatera Utara)&mdash;konsultansi ini menyediakan dukungan independen untuk perlindungan sosial, pengadaan tanah, dan perencanaan pemulihan penghidupan. Penugasan ini mencakup survei dan analisis komprehensif atas tanah dan aset terdampak, penyusunan dokumen LARAP dan DPPT, analisis responsif gender atas dampak terhadap komunitas dan rumah tangga, keterlibatan pemangku kepentingan, inventarisasi aset/tanaman (IOL), dan perancangan mekanisme penanganan keluhan.</p>
<p style="text-align: justify;" data-start="1314" data-end="1806">Metodologi memadukan verifikasi lapangan, pengumpulan data demografis dan sosial-ekonomi (dengan indikator terpilah gender), pemetaan tata guna dan kepemilikan lahan, kajian dampak komunitas dari pekerjaan intake dan transmisi infrastruktur, serta penyusunan langkah mitigasi dan pemulihan yang selaras dengan kerangka regulasi Indonesia dan standar perlindungan internasional (misalnya, Asian Development Bank Safeguard Policy Statement).</p>
<p style="text-align: justify;" data-start="1808" data-end="1826">Keluaran mencakup:</p>
<ul style="text-align: justify;" data-start="1827" data-end="2368">
<li data-start="1827" data-end="1951">
<p data-start="1829" data-end="1951">Laporan LARAP terperinci dan DPPT (Dokumen Perencanaan Pengadaan Tanah) untuk setiap sistem (Kertasari, Jatigede, Lau Simeme)</p>
</li>
<li data-start="1952" data-end="2090">
<p data-start="1954" data-end="2090">Laporan analisis responsif gender yang mengintegrasikan dampak terhadap perempuan, kelompok rentan, dan proses pengambilan keputusan pada tingkat rumah tangga</p>
</li>
<li data-start="2091" data-end="2159">
<p data-start="2093" data-end="2159">Kerangka keterlibatan pemangku kepentingan dan mekanisme penanganan keluhan</p>
</li>
<li data-start="2160" data-end="2236">
<p data-start="2162" data-end="2236">Data dasar sosial-ekonomi dan inventarisasi kerugian (tanah, bangunan, tanaman)</p>
</li>
<li data-start="2237" data-end="2368">
<p data-start="2239" data-end="2368">Rekomendasi strategis untuk mendukung implementasi investasi infrastruktur air baku yang aman, berkeadilan, dan berkelanjutan</p>
</li>
</ul>
<p style="text-align: justify;" data-start="2370" data-end="2666">Pekerjaan ini mendukung tujuan untuk memastikan bahwa sistem intake dan transmisi air baku tidak hanya layak secara teknis dan finansial, tetapi juga bertanggung jawab secara sosial&mdash;memastikan kompensasi yang adil, pemulihan penghidupan, kesetaraan gender, partisipasi masyarakat, dan dampak sosial negatif yang minimal.</p>',
            ],
            'environmental-and-social-impact-assessment-esia-and-supplementary-studies-in-accordance-with-the-international-standards-equator-principles-and-ifc-performance-standards' => [
                'name_id' => 'Environmental and Social Impact Assessment (ESIA) dan studi pelengkap sesuai dengan standar internasional (Equator Principles dan IFC Performance Standards)',
                'description_id' => '<p style="text-align: justify;">Penugasan ini mencakup pelaksanaan <strong data-start="764" data-end="815">Environmental &amp; Social Impact Assessment (ESIA)</strong> yang komprehensif beserta studi perlindungan terkait untuk pengembangan industri/pengolahan nikel oleh IHIP &amp; HNI di Sulawesi Selatan. Konsultansi ini mencakup penyusunan LARAP, survei dampak sosial, ekonomi, dan pengadaan tanah, keterlibatan pemangku kepentingan, perancangan mekanisme penanganan keluhan (GRM), serta jaminan kepatuhan terhadap standar internasional (Equator Principles dan IFC Performance Standards). Tujuannya adalah mendukung klien dalam melaksanakan proyek secara bertanggung jawab secara sosial dan berkelanjutan secara lingkungan, dengan memastikan bahwa pengadaan tanah, permukiman kembali, dampak komunitas, dan risiko lingkungan dikelola sesuai praktik terbaik internasional.</p>',
            ],
            'preparation-of-land-acquisition-planning-document-dppt-and-feasibility-study-for-kebagusan-south-jakarta-jati-kramat-east-jakarta-and-duren-tiga-south-jakarta-reservoir-development-plan' => [
                'name_id' => 'Penyusunan Dokumen Perencanaan Pengadaan Tanah (DPPT) dan Studi Kelayakan untuk Rencana Pengembangan Waduk Kebagusan, Jati Kramat, dan Duren Tiga di DKI Jakarta',
                'description_id' => '<p style="text-align: justify;" data-start="607" data-end="930">Konsultansi ini mendukung <strong data-start="637" data-end="714">Dinas Sumber Daya Air (Dinas SDA) Pemerintah Provinsi DKI Jakarta</strong> dalam penyusunan <strong data-start="741" data-end="767">Studi Kelayakan (FS)</strong> dan <strong data-start="772" data-end="818">Dokumen Perencanaan Pengadaan Tanah (DPPT)</strong> untuk rencana pengembangan tiga waduk perkotaan strategis: <strong data-start="885" data-end="927">Kebagusan, Jati Kramat, dan Duren Tiga</strong>.</p>
<p style="text-align: justify;" data-start="932" data-end="1345">Studi ini bertujuan mengkaji kelayakan teknis, lingkungan, dan sosial-ekonomi pembangunan waduk sebagai bagian dari inisiatif mitigasi banjir dan pengelolaan sumber daya air Jakarta. Komponen DPPT berfokus pada identifikasi bidang tanah terdampak, struktur kepemilikan, dan estimasi kebutuhan kompensasi sesuai dengan kerangka pengadaan tanah Indonesia dan prinsip perlindungan sosial.</p>
<p style="text-align: justify;" data-start="1347" data-end="1632">Melalui analisis terpadu yang mencakup aspek rekayasa, lingkungan, dan sosial, proyek ini menyediakan fondasi perencanaan yang komprehensif untuk pengembangan waduk perkotaan yang berkelanjutan&mdash;mendukung peningkatan kapasitas pengendalian banjir, pengisian ulang air tanah, dan keamanan air di Jakarta.</p>',
            ],
            'preparation-of-masterplan-document-kkpr-and-industrial-business-license-iuiiuki-management-for-takalar-industrial-area' => [
                'name_id' => 'Penyusunan Dokumen Masterplan, KKPR dan Pengurusan Izin Usaha Industri (IUI/IUKI) untuk Kawasan Industri Takalar',
                'description_id' => '<p style="text-align: justify;" data-start="565" data-end="1045">Konsultansi ini berfokus pada <strong data-start="597" data-end="639">penyusunan dokumen masterplan</strong> dan <strong data-start="644" data-end="696">pengurusan persyaratan tata ruang dan perizinan</strong> untuk pengembangan <strong data-start="724" data-end="751">Kawasan Industri Takalar</strong> di Sulawesi Selatan. Penugasan ini mencakup penyusunan <strong data-start="809" data-end="835">Studi Kelayakan (FS)</strong>, perolehan <strong data-start="851" data-end="899">KKPR (Kesesuaian Kegiatan Pemanfaatan Ruang)</strong>, dan pengurusan proses <strong data-start="918" data-end="960">Izin Usaha Industri (IUI/IUKI)</strong> sesuai dengan regulasi nasional dan kebijakan pembangunan daerah.</p>
<p style="text-align: justify;" data-start="1047" data-end="1415">Proyek ini bertujuan menyediakan kerangka tata ruang, teknis, dan regulasi yang komprehensif untuk mendukung pertumbuhan berkelanjutan zona industri Takalar sebagai pusat investasi regional yang strategis. Studi ini mencakup analisis kesesuaian lokasi, perencanaan tata letak infrastruktur, pertimbangan lingkungan dan sosial, serta integrasi dengan program pembangunan ekonomi lokal.</p>
<p style="text-align: justify;" data-start="1417" data-end="1718">Melalui pekerjaan ini, konsultansi mendukung percepatan kesiapan kawasan industri dengan memastikan kepatuhan terhadap sistem perizinan Indonesia (OSS RBA), meningkatkan kelayakan investasi, serta mendorong pembangunan industri yang seimbang dan selaras dengan prinsip tata kelola lingkungan dan tata ruang.</p>',
            ],
            'land-analysis-and-soil-sample-collection-project-in-central-and-east-java' => [
                'name_id' => 'Proyek Analisis Lahan dan Pengambilan Sampel Tanah di Jawa Tengah dan Jawa Timur',
                'description_id' => '<p style="text-align: justify;" data-start="491" data-end="947">Proyek ini mencakup pelaksanaan <strong data-start="526" data-end="578">analisis kesesuaian lahan dan tanah yang komprehensif</strong> untuk mendukung <strong data-start="594" data-end="659">studi kelayakan pengembangan pertanian dan perkebunan</strong> di sejumlah lokasi terpilih di Jawa Tengah dan Jawa Timur. Konsultansi ini mencakup <strong data-start="731" data-end="820">survei lapangan, pengambilan sampel tanah, pengujian laboratorium, dan evaluasi lahan spasial</strong> untuk menentukan karakteristik fisik dan kimia tanah serta kesesuaiannya bagi berbagai jenis tanaman dan tata guna lahan.</p>
<p style="text-align: justify;" data-start="949" data-end="1319">Analisis ini berfokus pada parameter seperti tekstur tanah, kesuburan, kapasitas drainase, tingkat pH, kandungan organik, dan topografi&mdash;yang dipadukan dengan pemetaan berbasis GIS dan interpretasi data spasial. Hasil studi akan menjadi masukan bagi perencanaan tata guna lahan, keputusan investasi pertanian, dan strategi pengelolaan sumber daya yang berkelanjutan di area perkebunan target.</p>
<p style="text-align: justify;" data-start="1321" data-end="1579">Dengan memadukan presisi ilmiah dan analitik spasial, proyek ini menyediakan data dasar yang andal bagi klien untuk mengoptimalkan pemanfaatan lahan dan memastikan perencanaan perkebunan yang bertanggung jawab secara lingkungan sesuai dengan prinsip pertanian berkelanjutan.</p>',
            ],
            'preparation-of-environmental-impact-assessment-amdal-document-for-the-rongkong-multipurpose-dam-project-south-sulawesi' => [
                'name_id' => 'Penyusunan Dokumen Analisis Mengenai Dampak Lingkungan (AMDAL) untuk Proyek Bendungan Serbaguna Rongkong, Sulawesi Selatan',
                'description_id' => '<p style="text-align: justify;" data-start="507" data-end="1017">Konsultansi ini berfokus pada <strong data-start="539" data-end="601">penyusunan Analisis Mengenai Dampak Lingkungan (AMDAL)</strong> dan dokumentasi pendukung untuk <strong data-start="639" data-end="676">Proyek Bendungan Serbaguna Rongkong</strong> yang berlokasi di Sulawesi Selatan. Penugasan ini mencakup studi rona lingkungan awal yang komprehensif, prakiraan dan evaluasi dampak, proses konsultasi publik, serta penyusunan rencana mitigasi dan pemantauan untuk memastikan bahwa pembangunan bendungan mematuhi regulasi lingkungan Indonesia maupun praktik baik internasional.</p>
<p style="text-align: justify;" data-start="1019" data-end="1394">Studi ini mengkaji potensi dampak terhadap hidrologi sungai, kualitas air, ekosistem akuatik, keanekaragaman hayati daratan, tata guna lahan, dan kondisi sosial di dalam area proyek. Studi ini juga mencakup penyusunan Rencana Pengelolaan Lingkungan (RKL) dan Rencana Pemantauan Lingkungan (RPL), beserta dokumentasi yang diperlukan untuk <strong data-start="1349" data-end="1391">Izin Lingkungan</strong>.</p>
<p style="text-align: justify;" data-start="1396" data-end="1678">Dengan memadukan pertimbangan rekayasa, lingkungan, dan sosial-ekonomi, proyek ini bertujuan menyediakan kerangka lingkungan yang ilmiah dan patuh regulasi untuk mendukung pembangunan dan pengoperasian bendungan yang berkelanjutan dan bertanggung jawab di Daerah Aliran Sungai Rongkong.</p>',
            ],
            'training-and-workshop-on-procedures-for-implementing-land-acquisition-for-development-for-the-public-interest-pln-updl-makassar-phase-i' => [
                'name_id' => 'Pelatihan dan Lokakarya tentang Prosedur Pelaksanaan Pengadaan Tanah bagi Pembangunan untuk Kepentingan Umum – PLN UPDL Makassar (Tahap I)',
                'description_id' => '<p data-start="686" data-end="993">Proyek ini mencakup perancangan dan penyelenggaraan <strong data-start="737" data-end="770">program pelatihan dan lokakarya</strong> yang berfokus pada <strong data-start="786" data-end="885">prosedur dan kerangka regulasi pengadaan tanah bagi pembangunan untuk kepentingan umum</strong> (<em data-start="887" data-end="944">Pengadaan Tanah bagi Pembangunan untuk Kepentingan Umum</em>), bekerja sama dengan <strong data-start="969" data-end="990">PLN UPDL Makassar</strong>.</p>
<p data-start="995" data-end="1420">Pelatihan ini memberikan peserta pemahaman komprehensif tentang <strong data-start="1072" data-end="1123">prosedur hukum, administratif, dan teknis</strong> dalam pengadaan tanah berdasarkan Undang-Undang No. 2/2012 dan peraturan pelaksananya. Program ini juga menekankan <strong data-start="1238" data-end="1327">koordinasi pemangku kepentingan, mekanisme kompensasi, pengelolaan penanganan keluhan (GRM)</strong>, serta <strong data-start="1333" data-end="1363">praktik perlindungan sosial</strong> yang relevan dengan proyek sektor infrastruktur dan energi.</p>
<p data-start="1422" data-end="1700">Melalui sesi interaktif dan diskusi berbasis kasus, lokakarya ini memperkuat kapasitas kelembagaan dan praktis personel PLN dalam mengelola pengadaan tanah secara efisien, transparan, dan patuh terhadap <strong data-start="1648" data-end="1697">hukum nasional dan prinsip perlindungan sosial</strong>.</p>',
            ],
            'ifc-gap-fulfilment-esialarap-study-for-the-pomalaa-high-pressure-acid-leach-hpal-nickel-project' => [
                'name_id' => 'IFC Gap Fulfilment (Studi ESIA–LARAP) untuk Proyek Nikel Pomalaa High Pressure Acid Leach (HPAL)',
                'description_id' => '<p data-start="659" data-end="1166">Konsultansi ini mendukung <strong data-start="689" data-end="747">Proyek Nikel Pomalaa High Pressure Acid Leach (HPAL)</strong> dengan melaksanakan <strong data-start="765" data-end="793">Studi IFC Gap Fulfilment</strong> yang berfokus pada perlindungan lingkungan dan sosial. Pekerjaan ini mencakup tinjauan dan pemutakhiran komprehensif atas <strong data-start="901" data-end="954">Environmental and Social Impact Assessment (ESIA)</strong> dan <strong data-start="959" data-end="1016">Land Acquisition and Resettlement Action Plan (LARAP)</strong> untuk memastikan kepatuhan penuh terhadap <strong data-start="1052" data-end="1081">IFC Performance Standards</strong>, <strong data-start="1087" data-end="1109">Equator Principles</strong>, dan regulasi lingkungan dan sosial Indonesia.</p>
<p data-start="1168" data-end="1655">Penugasan ini mencakup verifikasi lapangan, konsultasi sosial-ekonomi dan pemangku kepentingan, kajian rona lingkungan awal, analisis kesenjangan antara studi eksisting dan persyaratan IFC, serta penyusunan rencana tindakan korektif. Proyek ini bertujuan memperkuat kerangka perlindungan operasi pengembangan nikel PT Vale Indonesia, dengan memastikan pengadaan tanah yang bertanggung jawab, keterlibatan masyarakat yang transparan, dan pengelolaan lingkungan yang berkelanjutan sepanjang siklus proyek.</p>
<p data-start="1657" data-end="1963">Dengan menyelaraskan dokumentasi dan praktik proyek dengan standar keberlanjutan internasional, studi ini berkontribusi pada uji tuntas (due diligence) lingkungan dan sosial yang diperlukan untuk pembiayaan internasional serta memperkuat komitmen PT Vale Indonesia terhadap operasi penambangan yang etis, transparan, dan berkelanjutan.</p>',
            ],
            'due-diligence-and-larap-preparation-for-the-pomalaa-high-pressure-acid-leach-hpal-nickel-project-international-finance-corporation-ifc' => [
                'name_id' => 'Due Diligence dan Penyusunan LARAP untuk Proyek Nikel Pomalaa High Pressure Acid Leach (HPAL) – International Finance Corporation (IFC)',
                'description_id' => '<p data-start="697" data-end="1101">Konsultansi ini menyediakan layanan <strong data-start="723" data-end="779">uji tuntas perlindungan sosial dan penyusunan LARAP</strong> untuk <strong data-start="797" data-end="828">Proyek Nikel Pomalaa HPAL</strong>, sebuah inisiatif strategis pengolahan nikel yang dikembangkan oleh PT Vale di Sulawesi Tenggara. Penugasan ini dilaksanakan dengan selaras dengan <strong data-start="963" data-end="992">IFC Performance Standards</strong>, <strong data-start="994" data-end="1016">Equator Principles</strong>, dan kerangka regulasi Indonesia yang mengatur pengadaan tanah dan permukiman kembali.</p>
<p data-start="1103" data-end="1573">Studi ini mencakup verifikasi proses pengadaan tanah, identifikasi orang dan aset yang terdampak proyek, kajian dampak penghidupan, serta penyusunan <strong data-start="1257" data-end="1314">Land Acquisition and Resettlement Action Plan (LARAP)</strong> yang konsisten dengan persyaratan IFC. Selain itu, studi ini mencakup konsultasi pemangku kepentingan, pengembangan mekanisme penanganan keluhan (GRM), dan penyusunan rencana tindakan korektif untuk menjembatani kesenjangan antara prosedur nasional dan praktik terbaik internasional.</p>
<p data-start="1575" data-end="1915">Melalui proses uji tuntas ini, proyek memastikan bahwa kegiatan pengadaan tanah dan permukiman kembali untuk fasilitas Pomalaa HPAL dilaksanakan secara transparan, berkeadilan, dan patuh terhadap standar keberlanjutan dan hak asasi manusia internasional &mdash; sehingga mendukung pembiayaan proyek yang etis dan keberlanjutan sosial jangka panjang.</p>',
            ],
            'adb-ta9861-ino-sustainable-infrastructure-assistance-program-phase-ii-supporting-sustainable-and-universal-electricity-access-phase-2-subproject-3' => [
                'name_id' => 'ADB TA-9861 INO: Sustainable Infrastructure Assistance Program Phase II - Supporting Sustainable and Universal Electricity Access Phase 2 (Subproject 3)',
                'description_id' => '<p style="text-align: justify;" data-start="797" data-end="1251">Proyek bantuan teknis di bawah <strong data-start="841" data-end="885">Asian Development Bank (ADB) TA-9861 INO</strong> ini mendukung <strong data-start="895" data-end="967">Phase II dari Sustainable Infrastructure Assistance Program (SIAP)</strong>, dengan fokus pada <strong data-start="981" data-end="1046">akses listrik yang berkelanjutan dan universal di seluruh Indonesia</strong>. Environmental and Social Safeguards Firm (JV PT Hatfield Indonesia) bertanggung jawab untuk mengembangkan, memutakhirkan, dan menyelaraskan instrumen perlindungan di seluruh inisiatif elektrifikasi nasional PLN.</p>
<p style="text-align: justify;" data-start="1253" data-end="1899">Penugasan ini mencakup penyusunan dan pengembangan kapasitas atas berbagai kerangka perlindungan, termasuk <strong data-start="1357" data-end="1413">Environmental and Social Management Framework (ESMF)</strong>, <strong data-start="1415" data-end="1468">Environmental and Social Impact Assessment (ESIA)</strong>, <strong data-start="1470" data-end="1527">Land Acquisition and Resettlement Action Plan (LARAP)</strong>, <strong data-start="1529" data-end="1567">Biodiversity Management Plan (BMP)</strong>, <strong data-start="1569" data-end="1613">Cultural Heritage Management Plan (CHMP)</strong>, <strong data-start="1615" data-end="1652">Stakeholder Engagement Plan (SEP)</strong>, dan <strong data-start="1658" data-end="1695">Grievance Redress Mechanism (GRM)</strong>. Penugasan ini juga mencakup pelatihan staf PLN dan pelaksana regional dalam penerapan ADB Safeguard Policy Statement (2009) dan regulasi nasional untuk memastikan kepatuhan dan akuntabilitas yang konsisten.</p>
<p style="text-align: justify;" data-start="1901" data-end="2175">Melalui dukungan teknis terpadu dan pengembangan kapasitas di lapangan, proyek ini memperkuat kesiapan kelembagaan PLN untuk mengimplementasikan infrastruktur energi yang berkelanjutan secara lingkungan, inklusif secara sosial, dan selaras dengan standar perlindungan internasional.</p>',
            ],
            'larap-preparation-and-land-acquisition-implementation-for-the-development-of-the-endikat-river-hydroelectric-power-plant-hepp' => [
                'name_id' => 'Penyusunan LARAP dan Pelaksanaan Pengadaan Tanah untuk Pengembangan Pembangkit Listrik Tenaga Air Sungai Endikat (HEPP)',
                'description_id' => '<p style="text-align: justify;" data-start="636" data-end="1040">Konsultansi ini menyediakan dukungan <strong data-start="662" data-end="758">penyusunan dan pelaksanaan Land Acquisition and Resettlement Action Plan (LARAP)</strong> untuk pengembangan <strong data-start="767" data-end="817">Endikat River Hydroelectric Power Plant (HEPP)</strong>. Proyek ini bertujuan memastikan bahwa proses pengadaan tanah dan permukiman kembali dilaksanakan secara transparan, berkeadilan, dan patuh sepenuhnya terhadap regulasi Indonesia dan standar perlindungan internasional.</p>
<p style="text-align: justify;" data-start="1042" data-end="1537">Penugasan ini mencakup survei sosial-ekonomi dan aset, konsultasi pemangku kepentingan, penyusunan kerangka kompensasi, program pemulihan penghidupan, serta pembentukan <strong data-start="1221" data-end="1259">Grievance Redress Mechanisms (GRM)</strong> dan <strong data-start="1264" data-end="1302">Stakeholder Engagement Plans (SEP)</strong>. Aspek lingkungan dan sosial juga dikaji melalui <strong data-start="1363" data-end="1416">Environmental and Social Impact Assessment (ESIA)</strong> dan <strong data-start="1421" data-end="1445">dokumentasi Izin Lingkungan</strong>, dengan memastikan bahwa baik ekosistem alami maupun kesejahteraan masyarakat terlindungi.</p>
<p style="text-align: justify;" data-start="1539" data-end="1905">Dengan mengintegrasikan prinsip perlindungan sosial ke dalam proses pengembangan pembangkit listrik tenaga air, proyek ini mendukung <strong data-start="1645" data-end="1678">PT Energi Banyu Kencana (EBK)</strong> dalam menghadirkan infrastruktur energi bersih yang tidak hanya andal secara teknis tetapi juga <strong data-start="1765" data-end="1864">bertanggung jawab secara sosial, berkelanjutan secara lingkungan, dan selaras dengan tujuan pembangunan inklusif</strong> di wilayah-wilayah kepulauan utama Indonesia.</p>',
            ],
            'construction-management-consultant-services-for-bara-lestari-housing-development-i-phase-ii-spph119251' => [
                'name_id' => 'Layanan Konsultan Manajemen Konstruksi untuk Bara Lestari Housing Development I – Phase II (SPPH-11925.1)',
                'description_id' => '<p style="text-align: justify;" data-start="556" data-end="832">Proyek ini menyediakan <strong data-start="578" data-end="626">layanan konsultansi manajemen konstruksi</strong> untuk <strong data-start="635" data-end="684">Bara Lestari Housing Development I &ndash; Phase II</strong>, sebuah proyek perumahan yang diprakarsai oleh PT Bukit Asam Tbk untuk mendukung kebutuhan perumahan masyarakat dan karyawan di sekitar area operasionalnya di Sumatera Selatan.</p>
<p style="text-align: justify;" data-start="834" data-end="1232">Konsultansi ini mencakup supervisi dan koordinasi seluruh kegiatan konstruksi, termasuk penjadwalan, kendali mutu, manajemen keselamatan, dan kepatuhan terhadap standar teknis dan lingkungan. Lingkup pekerjaan juga mencakup pemantauan kinerja kontraktor, verifikasi spesifikasi material, dan memastikan penyelesaian proyek yang tepat waktu dan efisien sesuai dengan desain dan anggaran yang disetujui.</p>
<p style="text-align: justify;" data-start="1234" data-end="1518">Melalui manajemen profesional dan pengawasan teknis, proyek ini bertujuan memastikan bahwa kompleks Perumahan Bara Lestari dibangun dengan standar konstruksi yang tinggi, mendukung <strong data-start="1412" data-end="1469">infrastruktur perumahan yang berkelanjutan, aman, dan layak huni</strong> bagi masyarakat lokal dan karyawan perusahaan.</p>',
            ],
            'consultation-services-on-socialization-public-consultation-to-fishermen-for-the-cirata-floating-solar-power-plant-project-2021-ifc' => [
                'name_id' => 'Layanan Konsultasi tentang Sosialisasi (Konsultasi Publik) kepada Nelayan untuk Proyek Cirata Floating Solar Power Plant (2021) – IFC',
                'description_id' => '<p style="text-align: justify;" data-start="624" data-end="1042">Konsultansi ini menyediakan <strong data-start="650" data-end="707">layanan konsultasi publik dan keterlibatan masyarakat</strong> bagi nelayan yang terdampak oleh <strong data-start="738" data-end="783">Proyek Cirata Floating Solar Power Plant</strong>, yang dikembangkan di bawah kerangka perlindungan lingkungan dan sosial IFC. Tujuan utamanya adalah memfasilitasi komunikasi yang transparan, menghimpun masukan, dan memastikan partisipasi yang bermakna dari komunitas nelayan lokal di sekitar Waduk Cirata di Jawa Barat.</p>
<p style="text-align: justify;" data-start="1044" data-end="1406">Kegiatan mencakup pemetaan pemangku kepentingan, penyusunan materi konsultasi, fasilitasi pertemuan publik, dokumentasi kekhawatiran masyarakat, dan penyusunan laporan ringkasan beserta rekomendasi untuk mengintegrasikan masukan nelayan ke dalam <strong data-start="1304" data-end="1361">Land Acquisition and Resettlement Action Plan (LARAP)</strong> dan <strong data-start="1366" data-end="1403">Grievance Redress Mechanism (GRM)</strong> proyek.</p>
<p style="text-align: justify;" data-start="1408" data-end="1655">Melalui keterlibatan ini, proyek memperkuat saling pengertian antara pengembang dan pemangku kepentingan lokal, mendorong <strong data-start="1532" data-end="1613">pengembangan energi terbarukan yang inklusif, bertanggung jawab secara sosial, dan berkelanjutan</strong> sesuai dengan IFC Performance Standards.</p>',
            ],
            'aap167568asatf0a7983-advisory-services-and-analytics-asa-country-safeguard-framework-assessment-csfa' => [
                'name_id' => 'AA-P167568-ASA-TF0A7983 – Advisory Services and Analytics (ASA): Country Safeguard Framework Assessment (CSFA)',
                'description_id' => '<p style="text-align: justify;" data-start="593" data-end="1024">Bantuan teknis di bawah program <strong data-start="629" data-end="683">Advisory Services and Analytics (ASA) World Bank</strong> ini berfokus pada pelaksanaan <strong data-start="716" data-end="765">Country Safeguard Framework Assessment (CSFA)</strong> untuk mengevaluasi sistem perlindungan lingkungan dan sosial Indonesia yang ada saat ini. Tujuannya adalah menilai keselarasannya dengan <strong data-start="895" data-end="952">Environmental and Social Framework (ESF) World Bank</strong> serta mengidentifikasi kesenjangan utama, kekuatan, dan area untuk peningkatan kapasitas.</p>
<p style="text-align: justify;" data-start="1026" data-end="1488">Kajian ini mencakup struktur hukum dan kelembagaan yang mengatur pengadaan tanah, permukiman kembali, masyarakat adat, pengelolaan lingkungan, dan keterlibatan pemangku kepentingan. Kajian ini juga memberikan rekomendasi kebijakan dan peta jalan implementasi untuk menyelaraskan kerangka perlindungan Indonesia dengan standar internasional, sekaligus memperkuat kemampuan lembaga nasional dalam mengelola risiko lingkungan dan sosial pada proyek infrastruktur dan pembangunan.</p>
<p style="text-align: justify;" data-start="1490" data-end="1724">Dengan memberikan wawasan analitis dan panduan strategis, proyek ini mendukung upaya berkelanjutan Indonesia menuju <strong data-start="1604" data-end="1678">tata kelola pembangunan yang berkelanjutan, inklusif, dan patuh perlindungan</strong> di bawah program kemitraan World Bank.</p>',
            ],
            'uklupl-application-document-preparation-services-for-forest-area-utilization-permit-pppkh-pt-dmp-gold-mining-exploration-activities-pt-woyla-aceh-minerals-jv-with-pt-ayamaru-bakti-pertiwi' => [
                'name_id' => 'Penyusunan Dokumen Permohonan UKL-UPL untuk Persetujuan Penggunaan Kawasan Hutan (PPPKH) - Eksplorasi Tambang Emas PT DMP (PT Woyla Aceh Minerals JV PT Ayamaru Bakti Pertiwi)',
                'description_id' => '<p style="text-align: justify;" data-start="706" data-end="1009">Konsultansi ini menyediakan <strong data-start="732" data-end="789">Layanan Penyusunan Dokumen Lingkungan (UKL-UPL)</strong> untuk mendukung permohonan <strong data-start="805" data-end="847">Persetujuan Penggunaan Kawasan Hutan (PPPKH)</strong> bagi kegiatan eksplorasi pertambangan emas yang dioperasikan oleh <strong data-start="911" data-end="921">PT DMP</strong> di bawah <strong data-start="928" data-end="954">PT Woyla Aceh Minerals</strong>, dalam joint venture dengan <strong data-start="978" data-end="1006">PT Ayamaru Bakti Pertiwi</strong>.</p>
<p style="text-align: justify;" data-start="1011" data-end="1411">Penugasan ini mencakup penyusunan dokumen pengelolaan lingkungan (UKL) dan pemantauan lingkungan (UPL) sesuai dengan persyaratan perizinan Kementerian Lingkungan Hidup dan Kehutanan (KLHK) dan provinsi. Studi ini mengkaji potensi dampak lingkungan dari pekerjaan eksplorasi, termasuk pembukaan lahan, pembangunan jalan akses, dan kegiatan pengeboran di dalam kawasan hutan yang ditetapkan.</p>
<p style="text-align: justify;" data-start="1413" data-end="1712">Dengan memastikan kepatuhan terhadap regulasi lingkungan dan persyaratan PPPKH, proyek ini memungkinkan klien memperoleh izin yang diperlukan untuk eksplorasi sekaligus mendorong <strong data-start="1587" data-end="1692">pengelolaan sumber daya mineral yang bertanggung jawab, perlindungan lingkungan, dan praktik kehutanan yang berkelanjutan</strong> di Provinsi Aceh.</p>',
            ],
            'ta8484-ino-sustainable-infrastructure-assistance-program-technical-assistance-cluster-management-facility-subproject-1-capacity-development-specialist-46380003' => [
                'name_id' => 'TA-8484 INO: Sustainable Infrastructure Assistance Program – Technical Assistance Cluster Management Facility (Subproject 1) – Capacity Development Specialist (46380-003)',
                'description_id' => '<p style="text-align: justify;" data-start="654" data-end="1324">Proyek bantuan teknis di bawah <strong data-start="694" data-end="756">Sustainable Infrastructure Assistance Program (SIAP) ADB</strong> ini berfokus pada penguatan kapasitas kelembagaan lembaga-lembaga infrastruktur Indonesia untuk merencanakan dan melaksanakan proyek sesuai dengan standar perlindungan lingkungan dan sosial. Sebagai <strong data-start="951" data-end="986">Capacity Development Specialist</strong>, konsultansi ini menyediakan dukungan advisori dan pelatihan untuk meningkatkan pemahaman dan penerapan instrumen perlindungan, termasuk <strong data-start="1127" data-end="1180">Environmental and Social Impact Assessment (ESIA)</strong>, <strong data-start="1182" data-end="1239">Land Acquisition and Resettlement Action Plan (LARAP)</strong>, <strong data-start="1241" data-end="1278">Stakeholder Engagement Plan (SEP)</strong>, dan <strong data-start="1284" data-end="1321">Grievance Redress Mechanism (GRM)</strong>.</p>
<p style="text-align: justify;" data-start="1326" data-end="1692">Penugasan ini mencakup perancangan modul pelatihan, penyelenggaraan lokakarya untuk lembaga pelaksana pusat dan daerah, serta penyusunan pedoman operasional untuk integrasi perlindungan ke dalam siklus proyek infrastruktur. Penugasan ini juga mendukung berbagi pengetahuan antara ADB dan mitra nasional untuk menyelaraskan praktik perlindungan Indonesia dengan standar internasional.</p>
<p style="text-align: justify;" data-start="1694" data-end="1942">Melalui inisiatif ini, program SIAP ADB membantu memajukan <strong data-start="1752" data-end="1830">pembangunan infrastruktur yang berkelanjutan, inklusif, dan patuh perlindungan</strong>, memperkuat tata kelola yang baik dan tanggung jawab lingkungan di seluruh portofolio investasi publik Indonesia.</p>',
            ],
            'land-acquisition-and-resettlement-action-plan-larap-for-pokko-hydroelectric-power-plant-world-bank' => [
                'name_id' => 'Land Acquisition and Resettlement Action Plan (LARAP) untuk Pokko Hydroelectric Power Plant – World Bank',
                'description_id' => '<p style="text-align: justify;" data-start="658" data-end="1171">Konsultansi ini berfokus pada penyusunan <strong data-start="721" data-end="778">Land Acquisition and Resettlement Action Plan (LARAP)</strong> yang komprehensif untuk <strong data-start="787" data-end="829">Pokko Hydroelectric Power Plant (HEPP)</strong> di Sulawesi Barat dan Sulawesi Selatan, yang didanai di bawah <strong data-start="875" data-end="911">kerangka perlindungan World Bank</strong>. Studi ini memastikan bahwa seluruh proses pengadaan tanah, permukiman kembali, dan pemulihan penghidupan mematuhi <strong data-start="1019" data-end="1076">World Bank Environmental and Social Standard 5 (ESS5)</strong> dan dilaksanakan secara transparan, berkeadilan, serta melalui konsultasi dengan masyarakat terdampak.</p>
<p style="text-align: justify;" data-start="1173" data-end="1637">Penugasan ini mencakup survei sosial-ekonomi dan aset, keterlibatan dan konsultasi pemangku kepentingan, identifikasi project-affected persons (PAPs), penyusunan <strong data-start="1341" data-end="1378">Livelihood Restoration Plan (LRP)</strong>, dan pembentukan <strong data-start="1405" data-end="1442">Grievance Redress Mechanism (GRM)</strong> dan <strong data-start="1447" data-end="1484">Stakeholder Engagement Plan (SEP)</strong>. Perhatian khusus diberikan pada pertimbangan <strong data-start="1516" data-end="1543">Indigenous Peoples (IP)</strong>, dengan memastikan bahwa langkah-langkah mitigasi sesuai secara budaya dan inklusif.</p>
<p style="text-align: justify;" data-start="1639" data-end="1923">Melalui LARAP ini, PLN dan World Bank bertujuan memastikan bahwa Pokko HEPP dikembangkan secara bertanggung jawab secara sosial dan berkelanjutan &mdash; menyeimbangkan pembangkitan energi bersih dengan kompensasi yang adil, partisipasi masyarakat, dan keamanan penghidupan jangka panjang bagi rumah tangga terdampak.</p>',
            ],
            'esia-training-batch-i' => [
                'name_id' => 'Pelatihan ESIA Batch I',
                'description_id' => '<p style="text-align: justify;" data-start="116" data-end="781">Pelatihan ESIA Batch I berhasil diselenggarakan sebagai program pelatihan publik pada 26&ndash;29 Februari 2024, yang disampaikan melalui platform daring untuk mengakomodasi peserta dari berbagai lokasi. Program ini mempertemukan 39 peserta yang mewakili beragam organisasi, termasuk perusahaan konsultan, badan usaha milik negara, dan profesional independen. Di antara lembaga yang berpartisipasi adalah SMEC Denka Indonesia, PT Inhutani I, PT Haskoning Indonesia, PT Hatfield Indonesia, PT SUCOFINDO, PT Indonesia Infrastructure Finance (PT IIF), dan PLN UIP JBB, yang mencerminkan minat lintas sektor yang kuat terhadap praktik tata kelola lingkungan dan sosial.</p>
<p style="text-align: justify;" data-start="783" data-end="1410">Tujuan utama pelatihan ini adalah meningkatkan pengetahuan dan pemahaman praktis peserta tentang Environmental and Social Impact Assessment (ESIA), sebuah komponen penting dalam memastikan pengembangan proyek yang berkelanjutan dan bertanggung jawab. Selama program empat hari, peserta terlibat dalam serangkaian sesi yang dipandu para ahli yang mencakup prinsip-prinsip utama ESIA, kerangka regulasi, identifikasi risiko, dan strategi mitigasi. Pelatihan ini juga menekankan penerapan dunia nyata melalui studi kasus dan diskusi interaktif, sehingga peserta dapat bertukar wawasan dan pengalaman dari bidang masing-masing.</p>
<p style="text-align: justify;" data-start="1412" data-end="1792">Kekuatan utama program ini adalah partisipasi dan keterlibatan aktif yang ditunjukkan para peserta. Format interaktif mendorong dialog yang bermakna, memungkinkan peserta memperdalam pemahaman sekaligus membangun koneksi profesional lintas sektor. Lingkungan pembelajaran kolaboratif ini berkontribusi signifikan terhadap efektivitas pelatihan secara keseluruhan.</p>
<p style="text-align: justify;" data-start="1794" data-end="2155" data-is-last-node="" data-is-only-node="">Secara keseluruhan, Pelatihan ESIA Batch I berhasil diselesaikan, mencapai tujuan yang ditetapkan dalam pengembangan kapasitas dan peningkatan pengetahuan. Program ini tidak hanya memperkuat kompetensi teknis peserta dalam ESIA tetapi juga menegaskan pentingnya mengintegrasikan pertimbangan lingkungan dan sosial ke dalam proses perencanaan dan implementasi proyek.</p>',
            ],
            'esia-training-batch-ii' => [
                'name_id' => 'Pelatihan ESIA Batch II',
                'description_id' => '<p style="text-align: justify;" data-start="119" data-end="692">Pelatihan ESIA Batch II berhasil diselenggarakan sebagai program pelatihan publik pada 2&ndash;6 September 2024, yang disampaikan melalui platform daring untuk memastikan aksesibilitas dan partisipasi yang luas. Batch ini mengalami peningkatan minat yang signifikan, dengan 52 peserta yang bergabung dari beragam lembaga, termasuk BPDLH, BNPB, PLN, IKI, berbagai organisasi konsultan, serta profesional independen. Keberagaman peserta menyoroti meningkatnya kesadaran dan permintaan akan penguatan tata kelola lingkungan dan sosial di berbagai sektor di Indonesia.</p>
<p style="text-align: justify;" data-start="694" data-end="1297">Pelatihan ini dirancang untuk memperdalam pemahaman dan penerapan praktis peserta atas Environmental and Social Impact Assessment (ESIA), dengan penekanan kuat pada penyelarasan praktik dengan standar internasional. Selama program lima hari, peserta dipaparkan materi komprehensif yang mencakup kerangka ESIA, metodologi kajian risiko, strategi keterlibatan pemangku kepentingan, dan perencanaan mitigasi. Wawasan dari lembaga keuangan internasional diintegrasikan ke dalam sesi-sesi tersebut, memberikan peserta perspektif global tentang persyaratan kepatuhan dan praktik terbaik.</p>
<p style="text-align: justify;" data-start="1299" data-end="1662">Ciri khas batch ini adalah keterlibatan praktisi berpengalaman yang berbagi studi kasus dunia nyata dan pelajaran yang dipetik dari implementasi proyek. Wawasan praktis ini memungkinkan peserta menjembatani kesenjangan antara teori dan praktik, membekali mereka dengan pengetahuan yang dapat langsung diterapkan dalam peran profesional masing-masing.</p>
<p style="text-align: justify;" data-start="1664" data-end="2060">Program ini juga menciptakan lingkungan pembelajaran yang dinamis melalui diskusi interaktif dan sesi berbagi pengetahuan. Peserta secara aktif menyumbangkan perspektif dari sektor masing-masing, memperkaya diskusi secara keseluruhan dan mendorong kolaborasi lintas sektor. Pertukaran gagasan ini memainkan peran krusial dalam memperkuat pemahaman kolektif tentang tantangan dan peluang ESIA.</p>
<p style="text-align: justify;" data-start="2062" data-end="2403" data-is-last-node="" data-is-only-node="">Secara keseluruhan, Pelatihan ESIA Batch II berhasil diselesaikan, semakin menegaskan pentingnya mengintegrasikan pertimbangan lingkungan dan sosial ke dalam proyek pembangunan. Program ini tidak hanya meningkatkan kapasitas teknis tetapi juga mendukung terbentuknya komunitas ESIA yang lebih terinformasi dan kolaboratif di berbagai industri.</p>',
            ],
            'esia-training-batch-iii' => [
                'name_id' => 'Pelatihan ESIA Batch III',
                'description_id' => '<p style="text-align: justify;" data-start="104" data-end="775">Pelatihan ESIA Batch III diselenggarakan sebagai program pelatihan publik pada 16&ndash;20 Juni 2025, yang disampaikan secara daring untuk memfasilitasi partisipasi profesional dari berbagai wilayah. Batch ini melibatkan 22 peserta yang mewakili kombinasi beragam organisasi, termasuk PT Indexim Coalindo, PT Kalimantan Energi Hijau, Asset Pacific Group, BRIN, PT Alam Hijau Konsultan, PT SMEC Denka Indonesia, PT Cedar Karyatama Lestarindo, dan PT Sucofindo Cabang Semarang. Meskipun jumlahnya lebih kecil dibandingkan batch sebelumnya, komposisi peserta mencerminkan keterlibatan yang lebih terfokus dan terspesialisasi dari sektor-sektor utama yang terlibat dalam tata kelola lingkungan dan sosial.</p>
<p style="text-align: justify;" data-start="777" data-end="1363">Pelatihan ini dirancang untuk memperkuat pengetahuan dan pemahaman praktis peserta atas Environmental and Social Impact Assessment (ESIA), dengan penekanan pada kedalaman teknis maupun penerapan dunia nyata. Selama lima hari, peserta mengikuti sesi terstruktur yang mencakup komponen inti ESIA, termasuk identifikasi dampak, kajian risiko, perencanaan pengelolaan, dan kerangka pemantauan. Program ini juga menyoroti pentingnya mengintegrasikan ESIA ke dalam siklus proyek untuk memastikan kepatuhan terhadap regulasi nasional maupun standar internasional.</p>
<p style="text-align: justify;" data-start="1365" data-end="1815">Aspek menonjol dari batch ini adalah kualitas diskusi dan pertukaran pengetahuan antarpeserta. Dengan kelompok yang lebih terkonsentrasi, lingkungan pembelajaran memungkinkan interaksi yang lebih mendalam, sehingga peserta dapat mengeksplorasi tantangan yang kompleks, berbagi pengalaman profesional, dan mengkaji secara kritis praktik ESIA di industri masing-masing. Kondisi ini menumbuhkan dinamika pembelajaran yang lebih intensif dan kolaboratif dibandingkan kelompok yang lebih besar.</p>
<p style="text-align: justify;" data-start="1817" data-end="2155">Selain itu, program ini mendorong peserta mengontekstualisasikan prinsip ESIA dalam realitas organisasi dan sektoral masing-masing. Dengan menjembatani konsep teoretis dan diskusi kasus praktis, peserta menjadi lebih siap menerapkan metodologi ESIA dalam menangani risiko lingkungan dan sosial pada proyek yang sedang berjalan maupun yang akan datang.</p>
<p style="text-align: justify;" data-start="2157" data-end="2464" data-is-last-node="" data-is-only-node="">Secara keseluruhan, Pelatihan ESIA Batch III berhasil diselesaikan, berkontribusi pada pengembangan kapasitas ESIA yang berkelanjutan di berbagai industri. Program ini menegaskan tidak hanya kompetensi teknis tetapi juga pentingnya dialog lintas sektor dalam memajukan implementasi proyek yang berkelanjutan dan bertanggung jawab.</p>',
            ],
            'inhouse-esia-training-for-pt-pln-nusantara-power' => [
                'name_id' => 'Pelatihan ESIA In-House untuk PT PLN Nusantara Power',
                'description_id' => '<div class="flex flex-col text-sm pb-25">
<section class="text-token-text-primary w-full focus:outline-none [--shadow-height:45px] has-data-writing-block:pointer-events-none has-data-writing-block:-mt-(--shadow-height) has-data-writing-block:pt-(--shadow-height) [&amp;:has([data-writing-block])&gt;*]:pointer-events-auto scroll-mt-[calc(var(--header-height)+min(200px,max(70px,20svh)))]" dir="auto" data-turn-id="request-WEB:171a371c-e862-4c9d-aa48-8c86b061d782-9" data-testid="conversation-turn-8" data-scroll-anchor="true" data-turn="assistant">
<div class="text-base my-auto mx-auto pb-10 [--thread-content-margin:var(--thread-content-margin-xs,calc(var(--spacing)*4))] @w-sm/main:[--thread-content-margin:var(--thread-content-margin-sm,calc(var(--spacing)*6))] @w-lg/main:[--thread-content-margin:var(--thread-content-margin-lg,calc(var(--spacing)*16))] px-(--thread-content-margin)">
<div class="[--thread-content-max-width:40rem] @w-lg/main:[--thread-content-max-width:48rem] mx-auto max-w-(--thread-content-max-width) flex-1 group/turn-messages focus-visible:outline-hidden relative flex w-full min-w-0 flex-col agent-turn">
<div class="flex max-w-full flex-col gap-4 grow">
<div class="min-h-8 text-message relative flex w-full flex-col items-end gap-2 text-start break-words whitespace-normal outline-none keyboard-focused:focus-ring [.text-message+&amp;]:mt-1" dir="auto" tabindex="0" data-message-author-role="assistant" data-message-id="19e57c99-1cbf-4a1a-a4b1-f243dade1ef2" data-message-model-slug="gpt-5-3" data-turn-start-message="true">
<div class="flex w-full flex-col gap-1 empty:hidden">
<div class="markdown prose dark:prose-invert w-full wrap-break-word dark markdown-new-styling">
<p style="text-align: justify;" data-start="139" data-end="557">Pelatihan ESIA In-House untuk PT PLN Nusantara Power berhasil diselenggarakan melalui platform daring, dengan melibatkan 30 peserta dari seluruh organisasi. Sebagai program pengembangan kapasitas internal yang khusus, pelatihan ini dirancang secara spesifik untuk menjawab konteks operasional, tantangan, dan prioritas strategis PT PLN Nusantara Power dalam mengelola aspek lingkungan dan sosial dalam proyek-proyeknya.</p>
<p style="text-align: justify;" data-start="559" data-end="1060">Program ini memberikan wawasan komprehensif tentang Environmental and Social Impact Assessment (ESIA), dengan fokus kuat pada penguatan pemahaman peserta atas kerangka ESIA, implementasi praktis, dan praktik terbaik yang selaras dengan standar internasional. Sepanjang pelatihan, peserta dipandu melalui komponen-komponen utama ESIA, termasuk identifikasi dampak, kajian risiko, perencanaan mitigasi, dan mekanisme pemantauan, yang seluruhnya dikontekstualisasikan dalam sektor energi.</p>
<p style="text-align: justify;" data-start="1062" data-end="1444">Penekanan utama pelatihan ini adalah menjembatani standar global dengan praktik organisasi. Dengan memasukkan perspektif dari kerangka internasional dan lembaga keuangan, program ini memungkinkan peserta lebih memahami persyaratan kepatuhan dan meningkatnya pentingnya tata kelola lingkungan dan sosial dalam pembiayaan proyek dan kinerja keberlanjutan.</p>
<p style="text-align: justify;" data-start="1446" data-end="1841">Format interaktif pelatihan mendorong partisipasi aktif, memungkinkan peserta terlibat dalam diskusi, berbagi pengalaman internal, dan mengeksplorasi tantangan dunia nyata yang dihadapi dalam lingkungan operasional mereka. Pertukaran pengetahuan ini tidak hanya memperdalam pemahaman teknis tetapi juga mendukung pengembangan pendekatan ESIA yang lebih praktis dan dapat diterapkan di dalam perusahaan.</p>
<p style="text-align: justify;" data-start="1843" data-end="2230" data-is-last-node="" data-is-only-node="">Secara keseluruhan, Pelatihan ESIA In-House untuk PT PLN Nusantara Power berhasil diselesaikan, berkontribusi pada penguatan kapasitas internal dalam mengelola risiko lingkungan dan sosial. Program ini menegaskan pentingnya mengintegrasikan prinsip ESIA ke dalam perencanaan dan pelaksanaan proyek, mendukung komitmen organisasi terhadap pengembangan energi yang berkelanjutan dan bertanggung jawab.</p>
</div>
</div>
</div>
</div>
<div class="mt-3 w-full empty:hidden">&nbsp;</div>
</div>
</div>
</section>
</div>',
            ],
            'pomalaa-high-pressure-acid-leach-hpal-nickel-project' => [
                'name_id' => 'Pomalaa High Pressure Acid Leach (HPAL) Nickel Project',
                'description_id' => '<p style="text-align: justify;" data-start="126" data-end="627">Penyusunan Land Acquisition and Resettlement Action Plan (LARAP) untuk Proyek Nikel Pomalaa HPAL dilaksanakan sebagai komponen penting untuk memastikan bahwa proses pengadaan tanah dilakukan secara terstruktur, transparan, dan bertanggung jawab secara sosial. LARAP berfungsi sebagai instrumen kunci untuk mengelola potensi dampak yang timbul dari pengadaan tanah, termasuk perpindahan, kehilangan aset, dan gangguan penghidupan, sekaligus memastikan perlakuan yang adil dan berkeadilan bagi masyarakat terdampak.</p>
<p style="text-align: justify;" data-start="629" data-end="1031">LARAP ini disusun dengan selaras dengan regulasi Indonesia yang berlaku serta standar internasional, khususnya IFC Performance Standard 5 tentang Land Acquisition and Involuntary Resettlement. Dengan mengintegrasikan kerangka nasional dan global, rencana ini bertujuan memenuhi persyaratan kepatuhan sekaligus mengadopsi praktik terbaik dalam melindungi hak dan kesejahteraan orang-orang yang terdampak.</p>
<p style="text-align: justify;" data-start="1033" data-end="1604">Lingkup LARAP mencakup serangkaian kegiatan komprehensif yang dirancang untuk menyediakan dasar implementasi yang akurat dan akuntabel. Kegiatan ini meliputi survei sensus terperinci untuk mengidentifikasi rumah tangga dan individu yang terdampak, proses inventarisasi dan penilaian aset untuk menentukan besaran kerugian, serta konsultasi pemangku kepentingan yang terstruktur untuk memastikan partisipasi dan transparansi yang inklusif. Selain itu, rencana ini menetapkan kerangka kompensasi yang jelas yang menguraikan kriteria kelayakan, entitlement matrix, dan mekanisme pembayaran secara adil dan konsisten.</p>
<p style="text-align: justify;" data-start="1606" data-end="2060">Di luar kompensasi, LARAP menekankan langkah-langkah pemulihan penghidupan untuk mendukung masyarakat terdampak dalam membangun kembali atau memperbaiki kondisi sosial-ekonomi mereka. Hal ini mencerminkan pergeseran dari pendekatan yang semata-mata kompensatif menuju kerangka yang lebih berorientasi pada pembangunan berkelanjutan. Rencana ini juga memuat mekanisme penanganan keluhan, yang memungkinkan pemangku kepentingan terdampak menyampaikan kekhawatiran dan mencari penyelesaian melalui proses yang terstruktur dan mudah diakses.</p>
<p style="text-align: justify;" data-start="2062" data-end="2430">Lebih lanjut, LARAP mendefinisikan pengaturan kelembagaan dan strategi implementasi, termasuk peran dan tanggung jawab, sistem pemantauan dan evaluasi, serta mekanisme pelaporan untuk memastikan akuntabilitas sepanjang siklus proyek. Elemen-elemen ini penting untuk memastikan bahwa komitmen yang diuraikan dalam rencana benar-benar diterjemahkan ke dalam praktik.</p>
<p style="text-align: justify;" data-start="2432" data-end="2786" data-is-last-node="" data-is-only-node="">Secara keseluruhan, penyusunan LARAP untuk Proyek Nikel Pomalaa HPAL menunjukkan komitmen yang kuat terhadap pengadaan tanah yang bertanggung jawab dan pengelolaan risiko sosial. Hal ini menegaskan pentingnya menyeimbangkan tujuan pengembangan proyek dengan perlindungan hak masyarakat, sehingga berkontribusi pada hasil proyek yang lebih berkelanjutan dan inklusif secara sosial.</p>',
            ],
            'esia-update-of-ulumbu-mataloko-geothermal-power-plant-exploration-and-its-associated-facilities' => [
                'name_id' => 'Pemutakhiran ESIA Eksplorasi Pembangkit Listrik Tenaga Panas Bumi Ulumbu & Mataloko serta Fasilitas Terkaitnya',
                'description_id' => '<p>Proyek ini mencakup pemutakhiran dan perluasan kerangka ESIA untuk mendukung transisi energi bersih Indonesia melalui pengembangan panas bumi. Lingkupnya meliputi identifikasi dan mitigasi risiko terkait emisi H2S, pengelolaan sumber daya air, keanekaragaman hayati, dan dampak komunitas. Proyek ini menuntut kepatuhan ketat terhadap KfW Sustainability Guidelines (2024), World Bank Environmental and Social Framework (ESF), standar ILO, dan regulasi Indonesia.</p>',
            ],
            'refinement-of-esia-esmp-for-sustainable-aviation-fuel-saf-ns1-project' => [
                'name_id' => 'Penyempurnaan ESIA & ESMP untuk Sustainable Aviation Fuel (SAF) NS-1 Project',
                'description_id' => '<p>Penyusunan dan penyempurnaan Initial Environmental and Social Examination (IESE) dan Environmental and Social Management Plan (ESMP) yang berdiri sendiri untuk Sustainable Aviation Fuel (SAF) NS-1 Project di Sei Mangkei, Sumatera Utara. Penugasan ini mencakup analisis kesenjangan cepat terhadap ADB Environmental and Social Framework (ESS 1&ndash;10), peningkatan data dasar lingkungan dan sosial, penyaringan keanekaragaman hayati, pemodelan udara dan kebisingan, keterlibatan pemangku kepentingan dan pengembangan mekanisme penanganan keluhan, serta konsolidasi lampiran hukum dan pendukung untuk memastikan kepatuhan terhadap regulasi Indonesia dan persyaratan ADB.</p>',
            ],
            'land-acquisition-training-for-public-interest-development' => [
                'name_id' => 'Pelatihan Pengadaan Tanah bagi Pembangunan untuk Kepentingan Umum',
                'description_id' => '<p>Penyelenggaraan pelatihan tentang pengadaan tanah bagi pembangunan infrastruktur untuk kepentingan umum, dengan fokus pada penerapan Peraturan Pemerintah No. 19 Tahun 2021 dan peraturan terkait. Pelatihan ini mencakup prosedur pengadaan tanah, proses pengadaan tanah skala kecil, sertifikasi tanah, dan studi kasus praktis. Pelatihan ini menerapkan pendekatan partisipatif dan pembelajaran orang dewasa (andragogi) untuk meningkatkan pemahaman dan kapasitas pemecahan masalah peserta.</p>',
            ],
            'formulation-of-environmental-carrying-and-assimilative-capacity-penyusunan-daya-dukung-dan-daya-tampung-lingkungan-hidup-d3tlh' => [
                'name_id' => 'Penyusunan Daya Dukung dan Daya Tampung Lingkungan Hidup (D3TLH)',
                'description_id' => '<p data-start="1327" data-end="1640">Penyusunan dokumen teknis Indeks Daya Dukung dan Daya Tampung Lingkungan Hidup (D3TLH) Provinsi Kalimantan Tengah. Studi ini berfungsi sebagai acuan teknis bagi pemerintah provinsi dan daerah dalam menilai daya dukung lingkungan dan mendukung perencanaan pembangunan yang berkelanjutan.</p>
<p data-start="1642" data-end="1952">Dokumen ini disusun berdasarkan data lingkungan yang tersedia dan dimaksudkan untuk memandu penyusunan kebijakan dengan mengintegrasikan pertimbangan ekologis ke dalam strategi pembangunan daerah, sambil mengakui keterbatasan terkait ketersediaan data dan variabilitas lokal.</p>',
            ],
            'provincial-environmental-protection-and-management-plan-rencana-perlindungan-pengelolaan-lingkungan-hidup-rpplh' => [
                'name_id' => 'Rencana Perlindungan & Pengelolaan Lingkungan Hidup (RPPLH) Provinsi',
                'description_id' => '<p data-start="1310" data-end="1536">Penyusunan Rencana Perlindungan dan Pengelolaan Lingkungan Hidup (RPPLH) jangka panjang untuk Provinsi Kalimantan Tengah sebagai instrumen strategis untuk mengintegrasikan pertimbangan lingkungan ke dalam perencanaan pembangunan daerah.</p>
<p data-start="1538" data-end="2047">Dokumen ini mencakup analisis rona lingkungan awal, kajian daya dukung dan daya tampung lingkungan, identifikasi isu lingkungan utama, serta penyusunan arah kebijakan, strategi, dan program untuk pengelolaan sumber daya alam yang berkelanjutan. Dokumen ini berfungsi sebagai acuan bagi penataan ruang, kebijakan sektoral, dan program pembangunan, dengan memastikan bahwa pemanfaatan sumber daya tetap berada dalam batas ekologis dan mendukung keberlanjutan jangka panjang.</p>',
            ],
            'inhouse-land-acquisition-for-public-interest-development-training-for-pt-geo-dipa-energi' => [
                'name_id' => 'Pelatihan In-House Pengadaan Tanah bagi Pembangunan untuk Kepentingan Umum untuk PT Geo Dipa Energi',
                'description_id' => '<p data-start="1150" data-end="1402">Penyelenggaraan pelatihan tentang pengadaan tanah bagi pembangunan untuk kepentingan umum untuk PT Geo Dipa Energi, dengan fokus pada penerapan Peraturan Pemerintah No. 19 Tahun 2021 dan penyelarasan dengan standar perlindungan internasional (IFC, World Bank, dan ADB).</p>
<p data-start="1404" data-end="1825">Pelatihan ini mencakup mekanisme pengadaan tanah, tahap perencanaan&ndash;persiapan&ndash;pelaksanaan, analisis kesenjangan antara regulasi Indonesia dan standar internasional, serta studi kasus praktis yang relevan dengan area proyek Geo Dipa. Pelatihan ini menerapkan pendekatan partisipatif dan pembelajaran orang dewasa (andragogi) untuk meningkatkan pemahaman praktis dan kapasitas pemecahan masalah peserta.</p>',
            ],
        ]);
    }
}
